nodeLinker: node-modules

# Uncomment the following lines to make the project self-contained. Keeps the `.yarn/cache` folder in the project root and does not use the global package cache.

# checksumBehavior: update
# compressionLevel: mixed
# enableGlobalCache: false
# enableImmutableInstalls: false
